name: camera_capture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  geolocator: ^10.0.1
  image_picker: ^1.0.4
  firebase_storage: ^11.2.7
  camera: ^0.10.5+4
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
